### ISSUE TITLE
detailData decoding

### ISSUE THREAD

**Issue by matvejs16** [zer0k-z/cs2-leaderboard-api-description#2]
Hey, can you give some example how to decode detailData in python?

**Comment by zer0k-z** [comment]
I have yet to manage to make it work in code because the bytes are trimmed off in some way and are only decodeable if I add some amount of null bytes before and/or after it, which I had to do by hand so far.

**Comment by matvejs16** [comment]
Oh, ok, because i also tried to work with this and I found some cases where getting data is working.
Can you add me in Discord to share some progress and try to find solution together?
Discord: matvejs16

**Comment by matvejs16** [comment]
> I have yet to manage to make it work in code because the bytes are trimmed off in some way and are only decodeable if I add some amount of null bytes before and/or after it, which I had to do by hand so far.

I made big progress in this so far, i need to fix one more thing and looks like I can get data from detailData, I think there is some missing data, but it's not critical

**Comment by dann2g** [comment]
@zer0k-z thanks for making this project. Where does this image come from?

https://github.com/zer0k-z/cs2-leaderboard-api-description/raw/main/enum.png

We are seeing an additional entry with the tag number 21 (this picture covers 15-20).

**Comment by zer0k-z** [comment]
@dann2g It comes from using IDA to reverse the client dll, the new tag is the "Region" tag. I updated the repo for the new tag.

**Comment by dann2g** [comment]
@zer0k-z Awesome! Thanks. The extra bits on the protobuf are because it's delimited. Not sure about Python but with protobufjs it works out the box with Message.decodeDelimited -- if you still haven't managed to get it working on your end.

**Comment by matvejs16** [comment]
> Message.decodeDelimited -- if you still haven't managed to get it working on your end.

That helped me a lot xD
Before I used to write some algorythm to manage it (First time tried to work with proto btw)

**Comment by zer0k-z** [comment]
> @zer0k-z Awesome! Thanks. The extra bits on the protobuf are because it's delimited. Not sure about Python but with protobufjs it works out the box with Message.decodeDelimited -- if you still haven't managed to get it working on your end.

I managed to figure out why it didn't work. The first byte is actually the header indicating the length of the real protobuf. I just updated the repo, it should be able to extract everything now.
